### ISSUE TITLE
FTC SDK 4.0

### ISSUE THREAD

**Issue by AndrewLuGit** [acmerobotics/road-runner-quickstart#1]
Do you plan on writing examples using the new features in the FTC SDK 4.0?

**Comment by rbrott** [comment]
By new features, I presume you are referring to the addition of a velocity feed forward term to the REV ExH firmware (and SDK). At the moment, I'm not planning on augmenting the quickstart to use the new firmware PIDF functionality because it actually offers no benefits (at least that I can think of) over my current recommendation. Although it may appear that the feed forward term allows for higher frequency motion profiling, there is still the same limit on sending setpoints (i.e., it takes the same amount of time to set a motor power in PID mode and to set a motor velocity in PIDF mode). The only situation in which there are actual tangible performance improvements is when profiling is done in the firmware (as in the Talon SRX motion magic mode). This doesn't appear to be the case; `RUN_TO_POSITION` seems to just generate velocity setpoints with a proportional loop.

Furthermore, I have several reservations about this change:

1. The units for the FF term are unclear and this is not something you want to "guess and check."
2. The absence of the firmware source precludes users from knowing what the code actually does (as opposed to this project).
3. The firmware isn't particularly stable, especially with regard to new features. (This somewhat goes along with the previous item.)
