### ISSUE TITLE
Problem with the Dashboard.

### ISSUE THREAD

**Issue by AbilityEdge** [acmerobotics/road-runner-quickstart#143]
[robotControllerLog.txt](https://github.com/acmerobotics/road-runner-quickstart/files/6461500/robotControllerLog.txt)
Hey!
I was trying to use the Dashboard here, and it wasn't quite working... you can choose and run opmodes on the Driver Station App freely, but when I try to open the Dashboard and want to run an opmode, the dashboard connects and disconnect from the robot very quickly in a loop, and then the robot tries to restart itself but it fails, and restarts and restarts...
here is the logcat from the Control Hub:

**Comment by rbrott** [comment]
The key message is `java.lang.IllegalArgumentException: Infinity is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method`.

One of your config variables is infinite; this is usually caused by a zero gear ratio (see the warning in [this LRR section](https://www.learnroadrunner.com/drive-constants.html#wheel-radius-gear-ratio-trackwidth)).

**Comment by AbilityEdge** [comment]
> The key message is `java.lang.IllegalArgumentException: Infinity is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method`.
> 
> One of your config variables is infinite; this is usually caused by a zero gear ratio (see the warning in [this LRR section](https://www.learnroadrunner.com/drive-constants.html#wheel-radius-gear-ratio-trackwidth)).

I checked the DriveConstants, and the StandardTrackingWheelLocalizer.... I see no value that is 0 except some of the PIDF values... Where can the problem be?

**Comment by rbrott** [comment]
Can you post the code of all files annotated with `@Config`?

**Comment by NoahBres** [comment]
@AbilityEdge It's not that your value is zero. It's that it evaluates to a zero because you're representing a fraction using integer division instead of doubles. It's not an inherently intuitive or obvious issue. See the example that Ryan linked for an example of the error:

![Screen Shot 2021-05-12 at 12 09 54 PM](https://user-images.githubusercontent.com/6739076/118016412-f7a15880-b31a-11eb-94e4-3f1b7b150807.jpg)

**Comment by EliorYousefi** [comment]
ohhh, sorry! thank you it works!!!!
