### ISSUE TITLE
Follower feedforward tuning

### ISSUE THREAD

**Issue by Calvin-Xu** [acmerobotics/road-runner-quickstart#30]
> The trajectory followers are controllers that compute the robot's velocity and acceleration from the current trajectory and current position (they fall into the category of reference trackers). Some of the followers in Road Runner use PID with VA feedforward terms ([the holonomic PIDVA trajectory follower source](https://github.com/acmerobotics/road-runner/blob/master/core/src/main/kotlin/com/acmerobotics/roadrunner/followers/HolonomicPIDVAFollower.kt) is pretty readable and understandable at a high level) while others use more sophisticated techniques.

_Originally posted by @rbrott in https://github.com/acmerobotics/road-runner-quickstart/issues/25#issuecomment-548991999_

Thank you, this is incredibly clarifying. The feedforward concept in `HolonomicPIDVAFollower` seems quite understandable, but we are a bit confused by the comment where `correctedVelocity` is calculated and applied:

> // note: feedforward is processed at the wheel level; velocity is only passed here to adjust the derivative term

Additionally, we want to make sure if the goals of `FollowerPIDTuner` is to tune `TRANSLATIONAL_PID` and `HEADING_PID` in `SampleMecanumDriveBase`? It was not completely clear in the docs but made sense to us. I thought that this should become a separate issue so that more people can find it.

**Comment by rbrott** [comment]
While the feedforward is applied at the end-effector level (i.e., the motor level) instead of the configuration level (i.e., the pose level), the velocity is passed to the PIDF controller to compute a proper derivative term (to make the position D term act more like a velocity P term, see [this line](https://github.com/acmerobotics/road-runner/blob/0316264d64264a242458c457f62946ef7cb5d679/core/src/main/kotlin/com/acmerobotics/roadrunner/control/PIDFController.kt#L120)). Otherwise the PIDF controller acts more like a PID controller with feedforward applied later in the drive classes.

> Additionally, we want to make sure if the goals of `FollowerPIDTuner` is to tune `TRANSLATIONAL_PID` and `HEADING_PID` in `SampleMecanumDriveBase`? It was not completely clear in the docs but made sense to us.

Yes, that's correct.
