### ISSUE TITLE
How do we use Actions without Init?

### ISSUE THREAD

**Issue by marvelsofmas** [acmerobotics/road-runner-quickstart#311]
Hey,

I am trying to follow along with the [action tab](https://rr.brott.dev/docs/v1-0/actions/). I am fairly lost. How am I supposed to run motor/servo commands by calling the action class without **init**?

This is the example given:
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/108832774/ab2b8a3a-7dc7-4454-aa19-c6385a764296)

This is what we have:
Robot Class:
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/108832774/e44c9c58-39a1-4855-97d5-c8d22aeec96b)

Auton Class:
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/108832774/00c52b02-aa13-47c8-8c46-8a9c23407a9c)

robot.groundWrist()....will never do anything. If I remove the method the class itself loses reference to the motor/servo commands. Thank you.

**Comment by marvelsofmas** [comment]
Nevermind, we figured it out. But seriously an absurd amount of boiler plate code to run what was originally dead simple with Trajectory sequences in 0.5.X.

**Comment by rbrott** [comment]
> Hey,
> 
> I am trying to follow along with the [action tab](https://rr.brott.dev/docs/v1-0/actions/). I am fairly lost.

Totally fair. That page is out of date, and I'm working to update it soon. 

> How am I supposed to run motor/servo commands by calling the action class without **init**?

As the error on the `@Override` annotation suggests, `init()` is no longer part of the `Action`. You should instead move all of that into `run()` along with `return false`. You can even shorten that into a lambda since `Action` is a SAM interface.

> Nevermind, we figured it out. But seriously an absurd amount of boiler plate code to run what was originally dead simple with Trajectory sequences in 0.5.X.

Sorry for the headache. In the future, feel free to post here earlier on. I'm happy to field any questions about RR 1.0. Hopefully the lambda tip reduces the boilerplate compared to trajectory sequences.
